/*

	Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/


import {expect} from 'chai';

describe('Problem 2', () => {
	it('Find the sum of even-valued fibs below 20.', () => {
		expect(sumOfEvenFibs(20)).to.equal(10);
	});
	it('Find the sum of even-valued fibs below 4 million.', () => {
		console.time('problem 2')
		expect(sumOfEvenFibs(4000000)).to.equal(4613732);
		console.timeEnd('problem 2')
	});
});

function * evenFibGen(threshold) {
	let fibIncrem = 1, swap;
	for (let i = 1; i < threshold;) {
		if(!(i % 2)) yield i
		swap = i
		i += fibIncrem
		fibIncrem = swap
	}
}

function sumOfEvenFibs(threshold) {
	let sum = 0
	for (let i of evenFibGen(threshold)) {
		sum += i
	}
	return sum
}
